name: Main CI CD
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
  Explore-Preparations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Linting
        run: echo "Linting..."
      
      - name: Testing
        run: echo "Testing..."
