name: Main CI CD
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
  Explore-Preparations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      
      - name: Setup env
        working-directory: ./src
        run: mv example.env .env

      - name: Installing libs
        working-directory: ./src
        run: pip install -r requirements.dev.txt

      - name: Linting
        working-directory: ./src
        run: ruff check . --select F401 --select F403 --quiet

      - name: Testing
        working-directory: ./src
        run: python manage.py test
