name: Main CI CD
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
      - uses: actions/checkout@v4
      - run: echo "Linting..."
      
      - name: Testing
      - uses: actions/checkout@v4
      - run: echo "Testing..."
