name: Main CI CD
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
  Explore-Preparations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - working-directory: ./src
      - run: pip install -r requirements.dev.txt
      - run: python manage.py test

