name: Main pipeline
run-name: main pipeline
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Stage lint
      - run: echo "successful linting"

      - name: Stage test
      - run: echo "successful test"