name: Main CI CD
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]

jobs:
  preparations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      
      - name: Setup env
        working-directory: ./src
        run: mv example.env .env

      - name: Installing libs
        working-directory: ./src
        run: pip install -r requirements.dev.txt

      - uses: src/test@v1
  
  test:
    needs: preparations
    runs-on: ubuntu-latest
    steps:
      - uses: src/test@v1
      - name: Testing
        working-directory: ./src
        run: python manage.py test
