name: Main CI CD
on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
jobs:
  Explore-Preparations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      
      - name: Setup env
        working-directory: ./src
        run: mv example.env .env

      - name: Installing libs
        working-directory: ./src
        run: pip install -r requirements.dev.txt

      - name: Linting
        working-directory: ./src
        run: ruff check . --select F401 --select F403 --quiet

      - name: Testing
        working-directory: ./src
        run: python manage.py test

      - name: Some
        run: echo ${{ secrets.HUB_USERNAME }}

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: xoriax
          password: d0cHu8P4ss

      - name: Preparing image
        run: docker build -t tests -f ./src/Dockerfile .

      - name: Tagging image
        run: docker image tag tests xoriax/tests:latest

      - name: Pushing image
        run: docker push xoriax/tests:latest
